package com.nepalicoders.kshitij.dailyaffirmations.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF3359b4)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFdae2ff)
val light_onPrimaryContainer = Color(0xFF00174b)
val light_secondary = Color(0xFFbe002d)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFffd9da)
val light_onSecondaryContainer = Color(0xFF400008)
val light_tertiary = Color(0xFF006e00)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFF87fd6f)
val light_onTertiaryContainer = Color(0xFF002200)
val light_error = Color(0xFFB3261E)
val light_errorContainer = Color(0xFFF9DEDC)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410E0B)
val light_background = Color(0xFFfbfdfd)
val light_onBackground = Color(0xFF191c1d)
val light_surface = Color(0xFFfbfdfd)
val light_onSurface = Color(0xFF191c1d)
val light_surfaceVariant = Color(0xFFE7E0EC)
val light_onSurfaceVariant = Color(0xFF49454F)
val light_outline = Color(0xFF79747E)
val light_inverseOnSurface = Color(0xFFeff1f1)
val light_inverseSurface = Color(0xFF2d3132)
val light_inversePrimary = Color(0xFFb1c5ff)
val light_shadow = Color(0xFF000000)

val dark_primary = Color(0xFFb1c5ff)
val dark_onPrimary = Color(0xFF002a78)
val dark_primaryContainer = Color(0xFF12409b)
val dark_onPrimaryContainer = Color(0xFFdae2ff)
val dark_secondary = Color(0xFFffb3b5)
val dark_onSecondary = Color(0xFF680014)
val dark_secondaryContainer = Color(0xFF920020)
val dark_onSecondaryContainer = Color(0xFFffd9da)
val dark_tertiary = Color(0xFF6bdf56)
val dark_onTertiary = Color(0xFF003a00)
val dark_tertiaryContainer = Color(0xFF005300)
val dark_onTertiaryContainer = Color(0xFF87fd6f)
val dark_error = Color(0xFFF2B8B5)
val dark_errorContainer = Color(0xFF8C1D18)
val dark_onError = Color(0xFF601410)
val dark_onErrorContainer = Color(0xFFF9DEDC)
val dark_background = Color(0xFF191c1d)
val dark_onBackground = Color(0xFFe0e3e3)
val dark_surface = Color(0xFF191c1d)
val dark_onSurface = Color(0xFFe0e3e3)
val dark_surfaceVariant = Color(0xFF49454F)
val dark_onSurfaceVariant = Color(0xFFCAC4D0)
val dark_outline = Color(0xFF938F99)
val dark_inverseOnSurface = Color(0xFF191c1d)
val dark_inverseSurface = Color(0xFFe0e3e3)
val dark_inversePrimary = Color(0xFF3359b4)
val dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)
